runtime: php
env: flex

runtime_config:
  document_root: .
  
network:
  instance_tag: webengineapp
  name: production-vpc
  subnetwork_name: europe-west1-internal-prod 
 
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.5